// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEG.MENU.Infraestructura.Context;

#nullable disable

namespace SEG.MENU.Migrations
{
    [DbContext(typeof(SeguridadQueryDBContext))]
    [Migration("20230522211017_FIRST")]
    partial class FIRST
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEG.MENU.Dominio.Entidades.Aplication", b =>
                {
                    b.Property<Guid>("AplicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaMaquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreaUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescAplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificaMaquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificaUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAplicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RutaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AplicacionId");

                    b.HasIndex("AplicacionId")
                        .IsUnique();

                    b.ToTable("Aplicacion", "menu");
                });
#pragma warning restore 612, 618
        }
    }
}
