// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEG.MENU.Infraestructura.Context;

#nullable disable

namespace SEG.MENU.Migrations.SeguridadCommandDB
{
    [DbContext(typeof(SeguridadCommandDBContext))]
    partial class SeguridadCommandDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEG.MENU.Dominio.Entidades.Aplication", b =>
                {
                    b.Property<Guid>("AplicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaMaquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescAplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificaMaquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAplicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RutaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AplicacionId");

                    b.HasIndex("AplicacionId")
                        .IsUnique();

                    b.ToTable("Aplicacion", "menu");
                });

            modelBuilder.Entity("SEG.MENU.Dominio.Entidades.Modulo", b =>
                {
                    b.Property<Guid>("AplicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaMaquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescModulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("IconoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconoPrefijo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificaMaquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("AplicacionId", "ModuloId")
                        .HasName("PK_Modulo");

                    b.ToTable("Modulo", "menu");
                });

            modelBuilder.Entity("SEG.MENU.Dominio.Entidades.Modulo", b =>
                {
                    b.HasOne("SEG.MENU.Dominio.Entidades.Aplication", "Apliation")
                        .WithMany("Modulos")
                        .HasForeignKey("AplicacionId")
                        .IsRequired()
                        .HasConstraintName("FK_Modulo_Aplication");

                    b.Navigation("Apliation");
                });

            modelBuilder.Entity("SEG.MENU.Dominio.Entidades.Aplication", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
